/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LayoutsDetault: typeof import('./src/components/layouts/layouts-detault.vue')['default']
    Login: typeof import('./src/components/login/login.vue')['default']
    Profile: typeof import('./src/components/profile/profile.vue')['default']
    ProfileFriends: typeof import('./src/components/profile/profile-friends/profile-friends.vue')['default']
    ProfileGifts: typeof import('./src/components/profile/profile-gifts/profile-gifts.vue')['default']
    ProfileSettings: typeof import('./src/components/profile/profile-settings/profile-settings.vue')['default']
    Registration: typeof import('./src/components/registration/registration.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/the-footer/the-footer.vue')['default']
    TheHeader: typeof import('./src/components/the-header/the-header.vue')['default']
    UiButton: typeof import('./src/components/ui/ui-button.vue')['default']
    UiCard: typeof import('./src/components/ui/ui-card.vue')['default']
    UiGrid: typeof import('./src/components/ui/ui-grid.vue')['default']
    WishList: typeof import('./src/components/wishlist/wish-list.vue')['default']
    WishListItem: typeof import('./src/components/wishlist/wish-list-item.vue')['default']
  }
}
