/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Erorr: typeof import('./src/components/layouts/erorr.vue')['default']
    LayoutsDetault: typeof import('./src/components/layouts/layouts-detault.vue')['default']
    Login: typeof import('./src/components/login/login.vue')['default']
    PageNotFound: typeof import('./src/components/layouts/pageNotFound.vue')['default']
    Registration: typeof import('./src/components/registration/registration.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/the-footer/the-footer.vue')['default']
    TheHeader: typeof import('./src/components/the-header/the-header.vue')['default']
    UiButton: typeof import('./src/components/ui/ui-button.vue')['default']
    WishList: typeof import('./src/components/wishlist/wish-list.vue')['default']
    WishListItem: typeof import('./src/components/wishlist/wish-list-item.vue')['default']
  }
}
